services:
  postgres:
    image: postgres:latest
    container_name: spess-cont
    environment:
       POSTGRES_DB: spess
       POSTGRES_USER: whiz
       POSTGRES_PASSWORD: whiz
    ports:
      - "2000:5432"
    restart: unless-stopped
